<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'CmsCldr\Mapping\CountryInterface'       => __DIR__ . '/src/CmsCldr/Mapping/CountryInterface.php',
    'CmsCldr\Mapping\LanguageInterface'      => __DIR__ . '/src/CmsCldr/Mapping/LanguageInterface.php',
    'CmsCldr\Mapping\RegionInterface'        => __DIR__ . '/src/CmsCldr/Mapping/RegionInterface.php',
    'CmsCldr\Mapping\ScriptInterface'        => __DIR__ . '/src/CmsCldr/Mapping/ScriptInterface.php',
    'CmsCldr\Mapping\SubdivisionInterface'   => __DIR__ . '/src/CmsCldr/Mapping/SubdivisionInterface.php',
    'CmsCldr\Mapping\TerritoryInterface'     => __DIR__ . '/src/CmsCldr/Mapping/TerritoryInterface.php',
    'CmsCldr\Module'                         => __DIR__ . '/src/CmsCldr/Module.php',
    'CmsCldr\Mvc\Controller\AdminController' => __DIR__ . '/src/CmsCldr/Mvc/Controller/AdminController.php',
    'CmsCldrTest\Framework\TestCase'         => __DIR__ . '/tests/Framework/TestCase.php',
    'CmsCldrTest\SampleTest'                 => __DIR__ . '/tests/SampleTest.php',
);
