<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'CmsCldr\Mapping\CountryInterface'               => __DIR__ . '/src/Mapping/CountryInterface.php',
    'CmsCldr\Mapping\LanguageInterface'              => __DIR__ . '/src/Mapping/LanguageInterface.php',
    'CmsCldr\Mapping\RegionInterface'                => __DIR__ . '/src/Mapping/RegionInterface.php',
    'CmsCldr\Mapping\ScriptInterface'                => __DIR__ . '/src/Mapping/ScriptInterface.php',
    'CmsCldr\Mapping\SubdivisionInterface'           => __DIR__ . '/src/Mapping/SubdivisionInterface.php',
    'CmsCldr\Mapping\TerritoryInterface'             => __DIR__ . '/src/Mapping/TerritoryInterface.php',
    'CmsCldr\Module'                                 => __DIR__ . '/src/Module.php',
    'CmsCldr\Mvc\Controller\AdminController'         => __DIR__ . '/src/Mvc/Controller/AdminController.php',
    'CmsCldr\Service\TerritoryServiceAwareInterface' => __DIR__ . '/src/Service/TerritoryServiceAwareInterface.php',
    'CmsCldr\Service\TerritoryServiceAwareTrait'     => __DIR__ . '/src/Service/TerritoryServiceAwareTrait.php',
    'CmsCldrTest\Framework\TestCase'                 => __DIR__ . '/tests/Framework/TestCase.php',
    'CmsCldrTest\SampleTest'                         => __DIR__ . '/tests/SampleTest.php',
);
